name: Terraform IaC

on:
 push:
   paths:
     - "iac/**"
     - ".github/workflows/terraform.yml"
 pull_request:
   paths:
     - "iac/**"
     - ".github/workflows/terraform.yml"
 workflow_dispatch: {}

jobs:
 terraform:
   runs-on: ubuntu-latest

   defaults:
     run:
       working-directory: iac

   steps:
     - name: Checkout
       uses: actions/checkout@v4

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}

     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3

     - name: Terraform fmt
       run: terraform fmt -check

     - name: Terraform init
       run: terraform init

     - name: Terraform validate
       run: terraform validate

     - name: Terraform plan
       run: terraform plan -out=tfplan

     # Apply only when you manually click "Run workflow"
     - name: Terraform apply
       if: github.event_name == 'workflow_dispatch'
       run: terraform apply -auto-approve tfplan
